server:
  port: 8089

spring:
  rabbitmq:
    host: 81.70.90.253
    port: 5672
    username: root
    password: modnim666666
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2
